server:
  port: 9005

spring:
  application:
    name: hello-board-article-read-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hello-board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
# 호출 정보
endpoints:
  hello-board-article-service:
    url: http://127.0.0.1:9000
  hello-board-comment-service:
    url: http://127.0.0.1:9001
  hello-board-like-service:
    url: http://127.0.0.1:9002
  hello-board-view-service:
    url: http://127.0.0.1:9003